dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
cache:
  - pip
install:
  - sudo apt-get install bedtools
  - pip install -r requirements.txt
script:
  - python -m unittest discover -s tests
